### ISSUE TITLE
Programmatically alter MOM_input config file

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6-examples#107]
It would be very useful for testing, alternative user interfaces and automated runs in general to be able to modify the MOM_input file programmatically (ideally in Python). In MOM5 we've been using Marshall's F90NML (https://pypi.python.org/pypi/f90nml), which is very useful. 

Presently MOM_input is very close to the standard config file format (or INI format) it is just missing section headers (instead it uses comments) and uses a mixture of C and Fortran comment styles rather than ';' or '#'. 

How do people feel about  converting the MOM_Input format to a standard? Then we can use libraries like this https://docs.python.org/3.3/library/configparser.html? I think this is preferable to writing new config file parsers. 

I imagine that the first step here would be to extend the Fortran parser so that it can handle / ignores the section headers and different comment style - then we can convert the MOM_input files as needed.

**Comment by adcroft** [comment]
It's a good idea BUT ...

There is already a project in modeling services to provide an FMS-wide standard format for parameters which will probably be JSON. However, we are not going to abandon the current format but rather support both - the parser can handle multiple formats (and a well kept secret is it also parses fortran namelists as a result of a wild idea to read MOM5 namelists!). The reason we will support both formats is simple - there are too many live-configurations out there that abandoning the existing format would be too disruptive.

We can consider adding a third format rather than replace an existing one. As you said, the similarity between MOM6 and INI means we could fairly easily add support for the INI:
- # is already a comment except for #override . If we were in INI-mode we'd have to find a way to flag special lines.
- ; is not used so could become a comment character.
- [section]'s would serve as blocks or simple as comment-like delimiters?
- Not sure how we would handle nested blocks (which the parser currently supports but is not used so could be discarded).

`MOM_input` is meant to be identical to `MOM_parameter_doc.short` except for the header. Unfortunately, because `MOM_input` get's edited independently and so we tend to let them decouple. Every now and then we have gone through and synced them, which is overdue now.

As Bob pointed out when the JSON idea was floated, why change a format that is working? It does work very well and is very human readable because it is efficient in usage of vertical space - JSON uses more lines to achieve the same.

FYI, we already have [examples of python](https://github.com/adcroft/MOM6_parameter_scanner) parsing the MOM6 parameter format. We use this tool to generate web-pages for comparing our CMIP6 configurations (the internal dora website). It hasn't been packaged as a stand-alone tool like f90nml but could be.

**Comment by nichannah** [comment]
Good answer, it seems that this is/has already been/being done.
