### ISSUE TITLE
remove vprec from CM4 diag table

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#15]
We are presently saving vprec (virtual precip associated with SSS restoring) in CM4.  This term is, correctly, zero for the CM4 simulations.  We should remove vprec from the diag table to save archive space, and remove an array that is identically zero for the coupled simulations.

**Comment by adcroft** [comment]
It was a flawed argument: we actually do not test the diag_table in OM4_025 during our development workflow because it takes too long to write the diagnostics for such a big model, relative to the short duration of the test. I think we should either move vprec into the XML or have a second diag_table of OM4-only diagnostics and have the OM4 XML concatenate them.
