### ISSUE TITLE
Change diag_table output frequency for vh fields

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6-examples#152]
OMIP requests basin-average overturning diagnostics at monthly time frequency.  Our diag_tables save vh, vhGM, and vhml in ocean_annual_z.  These need to be moved to ocean_month_z.

**Comment by adcroft** [comment]
Should this be "vmo" rather than "vh"?

**Comment by MJHarrison-GFDL** [comment]
Should be 'vmo'. It's saving monthly 'vo', are you proposing saving monthly 'vo' and 'vmo'?

**Comment by StephenGriffies** [comment]
We need transport, which includes the area of the cell face. vmo is what we need for overturning transport.  

"vo" is velocity.  It is also needed for CMIP6.

So yes, we need to save both vmo and vo.

**Comment by jkrasting** [comment]
@adcroft and @StephenGriffies -- yes it should be vmo instead of vh and it should be saved monthly. 

After reading NOAA-GFDL/MOM6#348, seems like 'vh' still has some issues.  Is there a reason we are still carrying it around in the diag_tables?

We need to report vhGM and vhml as the CMIP6 diagostics msftyzmpa and msftyzsmpa, respectively.  Are they also incorrect in the code?

**Comment by adcroft** [comment]
Not sure why it's still in the diag_table. The currently analysis is using "vmo" if it's present (which is is):
https://github.com/NOAA-GFDL/MOM6-examples/blob/dev/gfdl/tools/analysis/meridional_overturning.py#L51-L56

We do not have msftyzmpa,... coded in the model because they are the result of zonal integration which will be handled by post-processing.

**Comment by adcroft** [comment]
My reading of NOAA-GFDL/MOM6#348 is that vmo is more correct than it was.

**Comment by jkrasting** [comment]
Yes, all of the overturning fields will be computed offline on a by-basin basis.

_(Try saying that 10 times fast :bowtie:)_

Here are the mappings that @StephenGriffies and I discussed last Friday:

1. msftyyz --> vh (*vmo per this thread now)
2. msftyzmpa --> vhGM (only pertains to the 0.5 degree model)
3. msftyzspma --> vhml

My question earlier was if vhGM and vhml suffer from the same problems as vh discussed in NOAA-GFDL/MOM6#348

**Comment by ashao** [comment]
@jkrasting, @adcroft: The problem of nonconservation mentioned in https://github.com/NOAA-GFDL/MOM6/pull/348, was rectified by making sure that the correct layer thicknesses were being passed to the diagnostic manager. The first of these changes were made in https://github.com/NOAA-GFDL/MOM6/commit/d41b04266ab736a7f9280d5cede113ddee6a8c2e.

Based on my reading of the code uhGM, vhGM, uhML, and vhML SHOULD be fine, but I will double-check and confirm that they are.

**Comment by ashao** [comment]
I just checked in a small test case (a 0.5 degree configuration of the Baltic test case) and the remapping for 'umo' and 'vmo' conserve just fine. The GM and ML components are not nearly as good, but it seems to be due to numerical deficiencies of the algorithm and not because of the mismatch with the thickness fields. 

@adcroft: The numerical deficiencies are due to discussions that we had earlier in the year about whether 1) we should add in a compensated sum to the reintegration algorithm and 2) add the difference between the original and reintegrated fields to the thickest cell of the destination column

**Comment by adcroft** [comment]
Do we need vhGM in ocean_month_z too? @StephenGriffies

**Comment by StephenGriffies** [comment]
yes

**Comment by adcroft** [comment]
Does everyone realize that vmo is "resolved + parameterized"?

Lines 7 and 9 in table I1 differ only in the j-direction coordinate. Do we have a means to provide line 7?

Given that monthly 3d output is very expensive, I am **not** adding umo, uhGM, uhml to ocean_month_*. Just vmo, vhGM, vhml, OK?

**Comment by StephenGriffies** [comment]
--The CMIP request is for the residual mean overturning, so that we need to include resolved+parameterized, so vmo is just what we need.  

--The CMIP request for both y- and meridional- transport is historical.  We have traditionally only provided the y-overturning (following model grid lines).  We do not have, nor do I recommend we develop, code to rotate from grid lines to true meridional. The only place there are differences is north of 65, where the transport is tiny anyhow.  Furthermore, the naive grid following zonal sums produce a physically relevant overturning.  So again, we are just doing the simple thing for CMIP, as it is more than sufficient for the science.  

--I request we save umo, uhGM, uhml as annual means.  They can be useful for some purposes, and annuals are not heavy duty.  BTW, can we also save vmo, vhGM, vhml as annuals as well as monthly?  Many purposes only need annual.

Steve

**Comment by StephenGriffies** [comment]
Furthermore, the bulk of interest in the overturning diagnostics are for long term means.  So annuals should be sufficient if there are archive space concerns.

**Comment by jkrasting** [comment]
Two issues - 

1.  vhgm and vhml units are meter3 second-1.  Can we make them 'kg s-1'?
2.  units string for 'vmo' is not CMOR compliant.  'kg/s' should be 'kg s-1'.

**Comment by adcroft** [comment]
1. We'll have to add new variables/diagnostics for kg s-1. Too much
analysis relies on the current units.
2. Can do.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by adcroft** [comment]
@jkrasting I stand corrected - I don't see vhGM/vhml in the automatic analysis because they're included in vmo. I think we did once but no longer...

**Comment by StephenGriffies** [comment]
We need the separate pieces for GM and submeso for OMIP/CMIP diagnostics.

**Comment by jkrasting** [comment]
Our analyses only consider vmo, which is the total.  We are to provide individual pieces to CMIP.  Converting vhGM and vhml to kg s-1 online would be ideal and safer.  Otherwise we need to do the conversion offline and I'd prefer not to hard code Rho_0 and Cp in the refineDiag script.

**Comment by jkrasting** [comment]
Just to clarify - Rho_0 applies to the overturning diagnostic.  Cp applies to one of the heat flux diagnostics that we should also convert online.  I'll open a separate issue for that.
