### ISSUE TITLE
Convert T_adx_2d and T_ady_2d to Watts

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6-examples#167]
The CMIP6 variables hfx and hfy are requested monthly in units of Watts.  This would currently require an offline units conversion that depends on Cp.  Since this is a runtime parameter that could potentially varying across experiments, this conversion should be done online in the model.

For the OM4_05 configuration with neutral diffusion:
     hfy =  T_ady_2d + ndiff_tracer_trans_y_2d_T

The ndiff_tracer_trans_y_2d_T diagnostic is already in units of Watts.

(Note: we will have to update the poleward heat transport diagnostic in tools/analysis)

**Comment by StephenGriffies** [comment]
Good suggestion.

**Comment by adcroft** [comment]
I think this is going to be a bit harder than you might imagine. neutral_diffusion posts it's own diagnostics which is why we controlled the units. Advection is posted by the tracer registry for which case-by-case unit conversion is not obvious...

**Comment by ashao** [comment]
@adcroft: The arrays that store the tendencies are allocated in the tracer registry, but changing the units should be easy because diagnostics themselves are registered: https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/core/MOM.F90#L2440-L2496. If we do this for vertical integrals of temperature, I presume that we should do this for the 3d fields as well.

Looking at these lines, both the advective fluxes and the diffusive fluxes (using strictly along-layer diffusion when neutral diffusion is not requested) also need to have the 'v_extensive = .true.' attribute added.

I'll have a PR ready to go later today if we want to go ahead with @jkrasting's suggestion
