### ISSUE TITLE
MOM6_DA_Hooks directory missing - gnu build instructions possibly obsolete?

### ISSUE THREAD

**Issue by ngs333** [NOAA-GFDL/MOM6-examples#324]
I am following the  MOM6-examples instructions for building the ocean-only MOM6-executable.
After a recursive git clone, I start following these instructions got gcc on Ubuntu linux:
https://github.com/NOAA-GFDL/MOM6-examples/wiki/Ubuntu-compiler-environment
and the step that the failure occurs are following these:
https://github.com/NOAA-GFDL/MOM6-examples/wiki/Ubuntu-compiler-environment#building-the-ocean-only-mom6-executable

The gcc compiler reports errors like:
Cannot open module file ‘generic_tracer.mod’.
Cannot open module file ‘ocean_da_types_mod.mod

After inspecting the cloned source code, I noticed that the directory MOM6_DA_Hooks is missing. My guess is there has been a version control related change and/or that the build instructions are out of date.

**Comment by adcroft** [comment]
@ngs33 That's my oversight - we moved things around so that the search path given to `list_pahts` must now include "config_src/external" (see #319). I did update the "Getting started" wiki page but forgot about this Ubuntu specific page. I just edited it so that the relevant line now reads
```
../../../../src/mkmf/bin/list_paths -l ./ ../../../../src/MOM6/{config_src/dynamic,config_src/solo_driver,config_src/external,src/{*,*/*}}/ ; \
```

So the build directions were out of date as you suggested. When paths are changed like this I recommend a clean build (i.e. remove the build directory for a fresh start).
