### ISSUE TITLE
Description/documentation of `idealized hurricane` example?

### ISSUE THREAD

**Issue by pittwolfe** [NOAA-GFDL/MOM6-examples#337]
Is there any documentation or description of the `idealized hurricane` ocean-only example? For example, a paper describing the experiment? I can't find anything.

Thanks!

**Comment by breichl** [comment]
Hi Christopher,

This example and the single column equivalent are loosely based on reproducing the Holland profile idealized hurricane configuration used in this study: https://journals.ametsoc.org/view/journals/mwre/144/12/mwr-d-16-0074.1.xml?tab_body=pdf

This particular example has not been used in any papers or otherwise documented, but if you have any specific questions feel free to reach out.
