### ISSUE TITLE
Thin layers are noisy in adiabatic mode

### ISSUE THREAD

**Issue by pittwolfe** [NOAA-GFDL/MOM6-examples#340]
I'm trying to run a simple Parsons-Veronis-type experiment: an adiabatic two-layer double gyre where the upper layer outcrops to create a detached western boundary current. The setup is a slight modification of the `double_gyre` example with different winds and initial layer configuration. It seems to work almost fine except that the upper layer doesn't fully vanish in the subpolar gyre but hovers around 1–2 m thickness with structured grid-scale noise.

![layer1](https://user-images.githubusercontent.com/4522204/128517652-4c21fdda-d308-4f01-8b42-8865f90ce1b8.png)
The above figure shows the upper layer thickness. It *looks* like the upper layer has vanished in the subpolar gyre, but adjusting the range of the color map shows that the upper layer is just fairly thin with a strange pattern of noise:
![layer1_zoom](https://user-images.githubusercontent.com/4522204/128517934-fa364943-2a5d-4e37-a20b-fb3483926336.png)

I suspect I'm violating some stability criterion when the layers get very thin, but I'm not sure which one. How do I get the upper layer to fully vanish (or at least achieve angstrom thickness)? Failing that, what should I do to suppress the noise in the thin layer?

Thanks!

The MOM_input file attached.
[MOM_input.txt](https://github.com/NOAA-GFDL/MOM6-examples/files/6945834/MOM_input.txt)

**Comment by marshallward** [comment]
@pittwolfe This is probably better discussed at the MOM6 community forums.  Would you mind reposting your issue there?

https://bb.cgd.ucar.edu/cesm/forums/mom6.148/

**Comment by Hallberg-NOAA** [comment]
@pittwolfe, I agree with @marshallward  that this would be most usefully discussed in the MOM6 community forum, but in the mean time, I do have an explanation for what is going on here.  In this two-layered case, because `DIRECT_STRESS = True` in your MOM_input file, the wind stress is being applied as a body force distributed over the topmost HMIX_STRESS (here 20 m) of water.  When the top layer gets thinner than this, a portion of the stress is instead applied to the second layer.  The Ekman transports that would make the topmost layer vanish in the subpolar gyre are increasingly occurring in the second layer once the topmost layer gets much thinner than 20 m (in a fraction of h_1 / HMIX_STRESS.

   There is also an elevated viscosity (KVML = 0.01 m2/s) applied at interfaces within the topmost HMIX_FIXED (also set to 20 m) of water, but the stress at this interface goes as Kv * (u1 - u2) / (0.5*(h1 + h2)), so in this two-layer limit, where 0.5*(h1+h2) is half the depth of the ocean, a large velocity difference between the layers is required to balance the wind stress. (For reference, 0.1 Pa * 1000m / (0.01 m2 s-1 * 1000 kg m-3) = 10 m s-1)  We do something clever (or unjustifiably invented-from-whole-cloth, depending on your viewpoint) near the bottom to reduce the length scales in the denominator of the stress term, but apart from under ice-shelves we don't do this at the surface.

  You can try setting DIRECT_STRESS = False, which I think will give you layers that really vanish in the subpolar gyre in your two-layer setup, but you should be prepared to get large velocities in the very thin or vanished topmost layer to have large velocities, and set your baroclinic timestep (DT) accordingly.

**Comment by StephenGriffies** [comment]
@pittwolfe please transfer this thread, with the response from @Hallberg-NOAA,  to the CESM/MOM6 forum for the benefit of the broader community.  Thanks!

**Comment by pittwolfe** [comment]
Thanks, will do!
