### ISSUE TITLE
Need help with grid configuration

### ISSUE THREAD

**Issue by suyashbire1** [NOAA-GFDL/MOM6-examples#42]
I have a setup with a spherical grid being forced by restoring buoyancy at the surface. This set up runs great. 

For my future runs, because my focus is on the eastern boundary (EB), I want to set up the grid such that zonal resolution is high near EB and becomes coarse as we go towards the west. Not being familiar with mosaic, I decided to meddle around with `MOM_grid_initialization.F90` to achieve this. 

I have questions about `dxC` and `dxB`. In `set_grid_metrics_spherical`, `dlon` is constant throughout. I have a varying `dlon`, which is used to set up `B` points. I compute `T` points as simply the midpoints of successive `B` points. So, in this case, how do I calculate `dxC` and `dxB`? Should they be centered, forward or backward?

Here's the routine I modified from `set_grid_metrics_spherical`. I don't know if there is a better way to do this? May be mosaic? It would be great if someone more proficient with MOM6 could help me out here. Please excuse me if I'm asking for too much. 

Suyash Bire
Stony Brook University

```fortran
subroutine set_grid_metrics_spherical_nonuniformx(G, param_file)
  type(ocean_grid_type), intent(inout) :: G
  type(param_file_type), intent(in)    :: param_file
! Arguments:
!  (inout)   G - The ocean's grid structure.
!  (in)      param_file - A structure indicating the open file to parse for
!                         model parameter values.

!    Calculate the values of the metric terms that might be used
!  and save them in arrays.
!    Within this subroutine, the x- and y- grid spacings and their
!  inverses and the cell areas centered on h, q, u, and v points are
!  calculated, as are the geographic locations of each of these 4
!  sets of points.
  real :: PI, PI_180! PI = 3.1415926... as 4*atan(1)
  integer :: i, j, isd, ied, jsd, jed
  integer :: is, ie, js, je, Isq, Ieq, Jsq, Jeq, IsdB, IedB, JsdB, JedB
  integer :: i_offset, j_offset, N
  real :: grid_latT(G%jsd:G%jed), grid_latB(G%JsdB:G%JedB)
  real :: grid_lonT(G%isd:G%ied), grid_lonB(G%IsdB:G%IedB)
  real :: dLon,dLat,latitude,longitude,dL_di, dLonmin, dLonmax
  character(len=48)  :: mod  = "MOM_grid_init set_grid_metrics_spherical_nonuniformx"

  is = G%isc ; ie = G%iec ; js = G%jsc ; je = G%jec
  isd = G%isd ; ied = G%ied ; jsd = G%jsd ; jed = G%jed
  Isq = G%IscB ; Ieq = G%IecB ; Jsq = G%JscB ; Jeq = G%JecB
  IsdB = G%IsdB ; IedB = G%IedB ; JsdB = G%JsdB ; JedB = G%JedB
  i_offset = G%isd_global - isd; j_offset = G%jsd_global - jsd

  call callTree_enter("set_grid_metrics_spherical_nonuniformx(), MOM_grid_initialize.F90")

!    Calculate the values of the metric terms that might be used
!  and save them in arrays.
  PI = 4.0*atan(1.0); PI_180 = atan(1.0)/45.

  call get_param(param_file, mod, "AXIS_UNITS", G%axis_units, default="degrees")
  if (trim(G%axis_units) == "") G%axis_units = "degrees"
  if (trim(G%axis_units) .ne. "degrees") call MOM_error(FATAL, &
    "MOM_grid_init.F90, set_grid_metrics_simple_spherical_nonuniformx: "// &
    "axis_units must be degrees")
  call get_param(param_file, mod, "SOUTHLAT", G%south_lat, &
                 "The southern latitude of the domain.", units="degrees", &
                 fail_if_missing=.true.)
  call get_param(param_file, mod, "LENLAT", G%len_lat, &
                 "The latitudinal length of the domain.", units="degrees", &
                 fail_if_missing=.true.)
  call get_param(param_file, mod, "WESTLON", G%west_lon, &
                 "The western longitude of the domain.", units="degrees", &
                 default=0.0)
  call get_param(param_file, mod, "LENLON", G%len_lon, &
                 "The longitudinal length of the domain.", units="degrees", &
                 fail_if_missing=.true.)
  call get_param(param_file, mod, "RAD_EARTH", G%Rad_Earth, &
                 "The radius of the Earth.", units="m", default=6.378e6)

  call get_param(param_file, mod, "DLON_MIN", dLonmin, &
                 "The desired minimum grid size in x direction.", units="degrees", &
                 fail_if_missing=.true.)

  N = G%Domain%niglobal
! dLon = G%len_lon/G%Domain%niglobal
! dLonmin is the resolution near the eastern boundary and dLonmax is the resolution 
! near the western boundary. dLonmax has to be calculated based upon domain length,
! number of grid points and dLonmin.
  dLonmax = (PI*G%len_lon - 2.0*(N)*dLonmin)/((N)*(PI-2.0))
  dLat = G%len_lat/G%Domain%njglobal

  do j=G%JsgB,G%JegB
    latitude = G%south_lat + dLat*(REAL(J-(G%jsg-1)))
    G%gridLatB(J) = MIN(MAX(latitude,-90.),90.)
  enddo
  do j=G%jsg,G%jeg
    latitude = G%south_lat + dLat*(REAL(j-G%jsg)+0.5)
    G%gridLatT(j) = MIN(MAX(latitude,-90.),90.)
  enddo
   do i=G%IsgB,G%IegB
    dlon = (dLonmin-dLonmax)*sin(i*PI/2.0/REAL(N)) + dLonmax
    if (i==G%IsgB) then
      G%gridLonB(I) = G%west_lon + dLon*(REAL(I-(G%isg-1)))
    else
      G%gridLonB(I) = G%gridLonB(I-1) + dLon
    endif
  enddo
  do i=G%isg,G%ieg
!    dlon = (dLonmin-dLonmax)*sin(i*PI/2.0/REAL(N)) + dLonmax
    if (i==G%isg) then
      G%gridLonT(i) = (G%west_lon + G%gridLonB(I))/2.0
    else
      G%gridLonT(i) = (G%gridLonB(I) + G%gridLonB(I-1))/2.0
    endif
  enddo

  do J=JsdB,JedB
    latitude = G%south_lat + dLat* REAL(J+J_offset-(G%jsg-1))
    grid_LatB(J) = MIN(MAX(latitude,-90.),90.)
  enddo
  do j=jsd,jed
    latitude = G%south_lat + dLat*(REAL(j+J_offset-G%jsg)+0.5)
    grid_LatT(j) = MIN(MAX(latitude,-90.),90.)
  enddo
  do I=IsdB,IedB
    dlon = (dLonmin-dLonmax)*sin(I*PI/2.0/REAL(N)) + dLonmax
    if (i==IsdB) then
      grid_LonB(I) = G%west_lon + dLon*REAL(I+I_offset-(G%isg-1))
    else
      grid_LonB(I) = grid_LonB(I-1) + dLon
    endif
  enddo
  do i=isd,ied
!    dlon = (dLonmin-dLonmax)*sin(i*PI/2.0/REAL(N)) + dLonmax
    if (i==isd) then
      grid_LonT(i) = (G%west_lon + grid_LonB(I))/2.0
    else
      grid_LonT(i) = (grid_LonB(i) + grid_LonB(i-1))/2.0
    endif
  enddo
!  dL_di = (G%len_lon * 4.0*atan(1.0)) / (180.0 * G%Domain%niglobal)
  do J=JsdB,JedB ; do I=IsdB,IedB
    G%geoLonBu(I,J) = grid_lonB(I)
    G%geoLatBu(I,J) = grid_latB(J)

    dlon = (dLonmin-dLonmax)*sin(i*PI/2.0/REAL(N)) + dLonmax
! The following line is needed to reproduce the solution from
! set_grid_metrics_mercator when used to generate a simple spherical grid.
!   G%dxBu(I,J) = G%Rad_Earth * COS( G%geoLatBu(I,J)*PI_180 ) * dL_di
    G%dxBu(I,J) = G%Rad_Earth * dLon*PI_180 * COS( G%geoLatBu(I,J)*PI_180 )
    G%dyBu(I,J) = G%Rad_Earth * dLat*PI_180
    G%areaBu(I,J) = G%dxBu(I,J) * G%dyBu(I,J)
  enddo; enddo

  do J=JsdB,JedB ; do i=isd,ied
    G%geoLonCv(i,J) = grid_LonT(i)
    G%geoLatCv(i,J) = grid_latB(J)

     dlon = (dLonmin-dLonmax)*sin(i*PI/2.0/REAL(N)) + dLonmax
! The following line is needed to reproduce the solution from
! set_grid_metrics_mercator when used to generate a simple spherical grid.
!   G%dxCv(i,J) = G%Rad_Earth * COS( G%geoLatCv(i,J)*PI_180 ) * dL_di
    G%dxCv(i,J) = G%Rad_Earth * (dLon*PI_180) * COS( G%geoLatCv(i,J)*PI_180 )
    G%dyCv(i,J) = G%Rad_Earth * dLat*PI_180
  enddo; enddo

  do j=jsd,jed ; do I=IsdB,IedB
    G%geoLonCu(I,j) = grid_lonB(I)
    G%geoLatCu(I,j) = grid_LatT(j)

    dlon = (dLonmin-dLonmax)*sin(i*PI/2.0/REAL(N)) + dLonmax
! The following line is needed to reproduce the solution from
! set_grid_metrics_mercator when used to generate a simple spherical grid.
!   G%dxCu(I,j) = G%Rad_Earth * COS( G%geoLatCu(I,j)*PI_180 ) * dL_di
    G%dxCu(I,j) = G%Rad_Earth * dLon*PI_180 * COS( G%geoLatCu(i,J)*PI_180 )
    G%dyCu(I,j) = G%Rad_Earth * dLat*PI_180
  enddo; enddo

  do j=jsd,jed ; do i=isd,ied
    G%geoLonT(i,j) = grid_LonT(i)
    G%geoLatT(i,j) = grid_LatT(j)
    dlon = (dLonmin-dLonmax)*sin(i*PI/2.0/REAL(N)) + dLonmax
! The following line is needed to reproduce the solution from
! set_grid_metrics_mercator when used to generate a simple spherical grid.
!   G%dxT(i,j) = G%Rad_Earth * COS( G%geoLatT(i,j)*PI_180 ) * dL_di
    G%dxT(i,j) = G%Rad_Earth * dLon*PI_180 * COS( G%geoLatT(i,j)*PI_180 )
    G%dyT(i,j) = G%Rad_Earth * dLat*PI_180

!   latitude = G%geoLatCv(i,J)*PI_180             ! In radians
!   dL_di    = G%geoLatCv(i,max(jsd,J-1))*PI_180  ! In radians
!   G%areaT(i,j) = Rad_Earth**2*dLon*dLat*ABS(SIN(latitude)-SIN(dL_di))
    G%areaT(i,j) = G%dxT(i,j) * G%dyT(i,j)
  enddo; enddo

  call callTree_leave("set_grid_metrics_spherical_nonuniformx()")
end subroutine set_grid_metrics_spherical_nonuniformx

```

**Comment by adcroft** [comment]
I think writing a custom grid routine for this task is the right approach. Generating mosaic files is not too hard but working with pre-processed files is more cumbersome if you want to change resolution regularly.

The expressions for gridLonB(I) in your code are assuming that dLon is uniform (because it is multiplied by REAL(I)).
```fortran
    dlon = (dLonmin-dLonmax)*sin(i*PI/2.0/REAL(N)) + dLonmax
    if (i==G%IsgB) then
      G%gridLonB(I) = G%west_lon + dLon*(REAL(I-(G%isg-1)))
    else
      G%gridLonB(I) = G%gridLonB(I-1) + dLon
    endif
```

What you are trying to do is a cumulative sum of dLon from the western most edge - which is challenging in a parallel environment. Instead, I recommend doing the math to calculate longitudes directly from "I" and then calculate dLon as the difference. It is not as accurate (because dLon is the difference of two numbers) but it will at least be consistent. e.g. To get `dx/di = b + c sin( pi*(i+G%isg)/N )` you want something like `x = a + b ( i+G%isg ) + c N/pi cos( pi*(i+G%isg)/N )`. In effect, this approximates your `sin` function as a difference of `cos`, which is quite reasonable here.

Concerning the dxBu and dxCu metrics, the [declaration comments](https://github.com/NOAA-GFDL/MOM6/blob/e47a5e8b3f7b1f0ca51d09a5a9b42e39532a9a9e/src/core/MOM_grid.F90#L104) are precise and there is a [schematic for those variables in MOM_grid_initialize.F90](https://github.com/NOAA-GFDL/MOM6/blob/e47a5e8b3f7b1f0ca51d09a5a9b42e39532a9a9e/src/initialization/MOM_grid_initialize.F90#L57). To calculate them, I would apply the expression above as a difference of longitudes at T points to get the distance centered at U and Q points, and difference the longitudes at U/Q points to get the distance at T,V points. Make sense?

Your question has suggested an interesting idea. As is done when reading mosaics, we could analytically define the supergrid (twice the resolution of the model grid) and then aggregate the supergrid appropriately into the B, T and U grids. This would make specifying these grids a lot simpler; you would only provide the corner positions of the double-resolution grid. _This last comment might not make sense without a lot more explanation but is here as a reminder to us to explore simplifying/unifying the grid initialization_.

**Comment by suyash309** [comment]
Thank you for your quick reply. 

> To get dx/di = b + c sin( pi*(i+G%isg)/N ) you want something like x = a + b ( i+G%isg ) + c N/pi cos( pi*(i+G%isg)/N ). In effect, this approximates your sin function as a difference of cos, which is quite reasonable here.

Yes, this is very clear, and I'll implement it as you suggest. I did a cumulative sum of all the `dlons` because I was unsure of what all the indices mean. For example, can you explain the difference between `isg` and `isd`? I see that `isg` is used for `gridlon` and `isd` for `geolon`. So, why is there a difference between `gridlon` and `geolon`? Also, why is `geolon` offset from `gridlon`?

> Concerning the dxBu and dxCu metrics, the declaration comments are precise and there is a schematic for those variables in MOM_grid_initialize.F90. To calculate them, I would apply the expression above as a difference of longitudes at T points to get the distance centered at U and Q points, and difference the longitudes at U/Q points to get the distance at T,V points. Make sense?

Thank you very much. What should I do for `dxBu/dxCu` at the eastern boundary, because there would be no V/T points to the east of Q/U points there?

> Your question has suggested an interesting idea. As is done when reading mosaics, we could analytically define the supergrid (twice the resolution of the model grid) and then aggregate the supergrid appropriately into the B, T and U grids.

Yes, this makes complete sense and is a much better way than taking midpoints of B points to get T points. In fact I was planning to do this myself. I just wanted to keep it simple for my first attempt.

**Comment by adcroft** [comment]
- isd is the locally referenced index of the start of the local array, ied is the end.
  - Declarations are typically isd:ied.
- isc is the locally referenced index of the start of the computational part of the local array, isc is the end.
  - Most loops are over isc:iec, or variants.
- The halo regions (copies of data from other processors) are the space isd:isc-1 and iec+1:ied.
- Thus, isd<isc<iec<ied, but all these indexes are local to the processor. The same values will appear on different processors for uniform parallel decompositions.
- isg is the absolute index of the first computational point in the local array.
  - Thus, i_absolute = (i - isc) + isg, when i is in a isc:iec loop.

The tricky part to get used to is that none of the above lets you work with a truly global array within one processor (which do not exist for good reason) so you always have to think about how to do things without relying on what might have happened earlier in a spatial loop (e.g. cumulative sums).

> So, why is there a difference between gridlon and geolon? Also, why is geolon offset from gridlon?

geoLon*, geoLat* are 2D arrays the model uses (e.g. to set Coriolis, do interpolation of forcing, ...). gridLon*, gridLat* are 1D arrays use solely for labelling diagnostic axes. You'll notice, unlike most arrays in the model, they are declared using isg:ieg, i.e. have completely different address spaces to the rest of the model. I think this is part of the API for the diag_manager, though I'm not sure (it predates me).

Side note: It has been a point of confusion about the output, arising from the CF standard, that these values are the model coordinates because they have geographic values even when the grid is not necessarily a spherical grid. We have been considering deliberately changing these values because so much "CF compliant" software misuses this data.

> What should I do for dxBu/dxCu at the eastern boundary, because there would be no V/T points to the east of Q/U points there?

It would be simplest to assume the grid is smooth and simply calculate those metrics as if the points did exist.

**Comment by suyash309** [comment]
Thank you very much. Documentation in `MOM_grid.F90` isn't very helpful when it comes to the difference between `isc` and `isd`. Your explanation makes it crystal clear that `isd:ied` also encompasses halo points along with computational points.

I still have doubts about `isg`. I understand that `isg` represents the global index of the first computational point in the local array. In that case, the following code from `set_grid_metrics_spherical` does not make sense to me.

```fortran
  do i=G%isg,G%ieg
    G%gridLonT(i) = G%west_lon + dLon*(REAL(i-G%isg)+0.5)
  enddo
``` 

Shouldn't this just be :
```fortran
  do i=G%isg,G%ieg
    G%gridLonT(i) = G%west_lon + dLon*(REAL(i)+0.5)
  enddo
``` 
Also, in the following snippet,
```fortran
  do i=isd,ied
    grid_LonT(i) = G%west_lon + dLon*(REAL(i+I_offset-G%isg)+0.5)
  enddo
```
suppose, `i=isd`, then `i+I_offset = G%isd_global`, which is less then `G%isg`. So, we're subtracting something from G%west_lon, which is quite confusing.

In the following snippet, `i` and `j` are local indices. So how are they being used to set global values in G%*?
```fortran
  do j=jsd,jed ; do i=isd,ied
    G%geoLonT(i,j) = grid_LonT(i)
    G%geoLatT(i,j) = grid_LatT(j)

! The following line is needed to reproduce the solution from
! set_grid_metrics_mercator when used to generate a simple spherical grid.
    G%dxT(i,j) = G%Rad_Earth * COS( G%geoLatT(i,j)*PI_180 ) * dL_di
!   G%dxT(i,j) = G%Rad_Earth * dLon*PI_180 * COS( latitude )
    G%dyT(i,j) = G%Rad_Earth * dLat*PI_180

!   latitude = G%geoLatCv(i,J)*PI_180             ! In radians
!   dL_di    = G%geoLatCv(i,max(jsd,J-1))*PI_180  ! In radians
!   G%areaT(i,j) = Rad_Earth**2*dLon*dLat*ABS(SIN(latitude)-SIN(dL_di))
    G%areaT(i,j) = G%dxT(i,j) * G%dyT(i,j)
  enddo; enddo
```
Please pardon me if I'm asking too many questions. I have spent a lot of time trying to come up with explanations myself but the indices still baffle me.

**Comment by adcroft** [comment]
I stand corrected about isg - it is **not** the global index of the first computational cell. isg is always=1 and ieg is always the global number of points. I was explaining how I would have defined things if I'd been involved in defining them - by bad! As it is, the code is creating global arrays which is something we want to avoid and will have to fix.

Here are the values for a 4 processor break down of double_gyre that uses a spherical grid with a halo of 4:
> PE=  0 isd=  1 isc=  5 isg=  1 isd_global= -3
> PE=  0 ied= 30 iec= 26 ieg= 44
> PE=  1 isd=  1 isc=  5 isg=  1 isd_global= 19
> PE=  1 ied= 30 iec= 26 ieg= 44
> PE=  2 isd=  1 isc=  5 isg=  1 isd_global= -3
> PE=  2 ied= 30 iec= 26 ieg= 44
> PE=  3 isd=  1 isc=  5 isg=  1 isd_global= 19
> PE=  3 ied= 30 iec= 26 ieg= 44

So the absolute index calculated from I = isc:iec (or I = isd:ied) is:
  **i_absolute = (i - isd) + isd_global**

so that PEs 0 and 3 have at i=isc i_absolute=1 and PEs 1 and 2 have at i=isc i_absolute=23

The models uses what is known as "north-east indexing" (u,v,q points are north-east of h,T points with the same index) so you will need to subtract 0.5 for the real(i) location of h-points.

I will correct my previous response also.

**Comment by adcroft** [comment]
Update on full-size global arrays: @Hallberg-NOAA , @MJHarrison-GFDL and I were looking at the interfaces to the diag_manager code (FMS) and have concluded that the axis data for diagnostics *does* need to be global. If such an array is needed for the diag_manager then there is no argument for not making use of the same during the grid initialization. This is not to say global 2D arrays should be allowed; @Zhi-Liang successfully removed any use of global 2D arrays when reading mosaics which were found to be causing slow initializations and to sometimes not fit in memory for high-resolution models.

**Comment by suyash309** [comment]
Thank you very much. That cleared it all up. So here's the final routine and it works like a charm.

```fortran
subroutine set_grid_metrics_spherical_nonuniformx(G, param_file)
  type(ocean_grid_type), intent(inout) :: G
  type(param_file_type), intent(in)    :: param_file
! Arguments:
!  (inout)   G - The ocean's grid structure.
!  (in)      param_file - A structure indicating the open file to parse for
!                         model parameter values.

!    Calculate the values of the metric terms that might be used
!  and save them in arrays.
!    Within this subroutine, the x- and y- grid spacings and their
!  inverses and the cell areas centered on h, q, u, and v points are
!  calculated, as are the geographic locations of each of these 4
!  sets of points.
  real :: PI, PI_180 ! PI = 3.1415926... as 4*atan(1)
  integer :: i, j, isd, ied, jsd, jed
  integer :: is, ie, js, je, Isq, Ieq, Jsq, Jeq, IsdB, IedB, JsdB, JedB
  integer :: i_offset, j_offset, i_global, N
  real :: grid_latT(G%jsd:G%jed), grid_latB(G%JsdB:G%JedB)
  real :: grid_lonT(G%isd:G%ied), grid_lonB(G%IsdB:G%IedB)
  real :: dLon,dLat,latitude,longitude,dL_di,dLonmin,dLonmaxsg,a,dLonminsg
  character(len=48)  :: mod  = "MOM_grid_init set_grid_metrics_spherical_nonuniformx"
  
  is = G%isc ; ie = G%iec ; js = G%jsc ; je = G%jec
  isd = G%isd ; ied = G%ied ; jsd = G%jsd ; jed = G%jed
  Isq = G%IscB ; Ieq = G%IecB ; Jsq = G%JscB ; Jeq = G%JecB
  IsdB = G%IsdB ; IedB = G%IedB ; JsdB = G%JsdB ; JedB = G%JedB
  i_offset = G%isd_global - isd; j_offset = G%jsd_global - jsd

  call callTree_enter("set_grid_metrics_spherical_nonuniformx(), MOM_grid_initialize.F90")

!    Calculate the values of the metric terms that might be used
!  and save them in arrays.
  PI = 4.0*atan(1.0); PI_180 = atan(1.0)/45.

  call get_param(param_file, mod, "AXIS_UNITS", G%axis_units, default="degrees")
  if (trim(G%axis_units) == "") G%axis_units = "degrees"
  if (trim(G%axis_units) .ne. "degrees") call MOM_error(FATAL, &
    "MOM_grid_init.F90, set_grid_metrics_simple_spherical_nonuniformx: "// &
    "axis_units must be degrees")

  call get_param(param_file, mod, "SOUTHLAT", G%south_lat, &
                 "The southern latitude of the domain.", units="degrees", &
                 fail_if_missing=.true.)
  call get_param(param_file, mod, "LENLAT", G%len_lat, &
                 "The latitudinal length of the domain.", units="degrees", &
                 fail_if_missing=.true.)
  call get_param(param_file, mod, "WESTLON", G%west_lon, &
                 "The western longitude of the domain.", units="degrees", &
                 default=0.0)
  call get_param(param_file, mod, "LENLON", G%len_lon, &
                 "The longitudinal length of the domain.", units="degrees", &
                 fail_if_missing=.true.)
  call get_param(param_file, mod, "RAD_EARTH", G%Rad_Earth, &
                 "The radius of the Earth.", units="m", default=6.378e6)
  call get_param(param_file, mod, "DLON_MIN", dLonmin, &
                 "The desired minimum grid size in x direction.", units="degrees", &
                 fail_if_missing=.true.)
  N = 2*G%Domain%niglobal     !number of grid points in supergrid
  dLonminsg = dLonmin/2.0     !dLonmin for supergrid
  dLonmaxsg = (PI*G%len_lon - 2.0*(N)*dLonminsg)/((N)*(PI-2.0))
  a = (dLonmaxsg - dLonminsg)*2*N/PI
  dLat = G%len_lat/G%Domain%njglobal

  do j=G%JsgB,G%JegB
    latitude = G%south_lat + dLat*(REAL(J-(G%jsg-1)))
    G%gridLatB(J) = MIN(MAX(latitude,-90.),90.)
  enddo
  do j=G%jsg,G%jeg
    latitude = G%south_lat + dLat*(REAL(j-G%jsg)+0.5)
    G%gridLatT(j) = MIN(MAX(latitude,-90.),90.)
  enddo
  do i=G%IsgB,G%IegB
     i_global = i-G%isg+1
     G%gridLonB(I) = G%west_lon + real(2*i_global)*dLonmaxsg+ &
                     a*(cos(real(2*i_global)*PI/real(N)/2.0)-1.0) 
  enddo
  do i=G%isg,G%ieg
     i_global = i-G%isg+1
     G%gridLonT(I) = G%west_lon + real(2*i_global-1)*dLonmaxsg + &
                     a*(cos(real(2*i_global-1)*PI/real(N)/2.0)-1.0)
  enddo
  do J=JsdB,JedB
    latitude = G%south_lat + dLat* REAL(J+J_offset-(G%jsg-1))
    grid_LatB(J) = MIN(MAX(latitude,-90.),90.)
  enddo
  do j=jsd,jed
    latitude = G%south_lat + dLat*(REAL(j+J_offset-G%jsg)+0.5)
    grid_LatT(j) = MIN(MAX(latitude,-90.),90.)
  enddo
  do I=IsdB,IedB
     i_global = i+I_offset-(G%isg-1)
     grid_LonB(I) = G%west_lon + real(2.0*i_global)*dLonmaxsg + &
                    a*(cos(real(2*(i_global))*PI/N/2.0)-1.0)
     WRITE(*,*) i,i_global,grid_LonB(i)
  enddo
  do i=isd,ied
     i_global = i+I_offset-(G%isg-1)
     grid_LonT(I) = G%west_lon + real(2.0*i_global-1)*dLonmaxsg + &
                    a*(cos(real(2*(i_global)-1)*PI/N/2.0)-1.0)
     WRITE(*,*) i,i_global,grid_LonT(i)
  enddo
  do J=JsdB,JedB ; do I=IsdB,IedB
    G%geoLonBu(I,J) = grid_lonB(I)
    G%geoLatBu(I,J) = grid_latB(J)
    
    i_global = i+I_offset-(G%isg-1)
    dlon = real(2.0*i_global+1)*dLonmaxsg+ a*(cos(real(2*(i_global)+1)*PI/N/2.0)-1.0) - &
           (real(2.0*i_global-1)*dLonmaxsg + a*(cos(real(2*(i_global)-1)*PI/N/2.0)-1.0))
    G%dxBu(I,J) = G%Rad_Earth * dLon*PI_180 * COS( G%geoLatBu(I,J)*PI_180 )
    G%dyBu(I,J) = G%Rad_Earth * dLat*PI_180
    G%areaBu(I,J) = G%dxBu(I,J) * G%dyBu(I,J)
  enddo; enddo
  do J=JsdB,JedB ; do i=isd,ied
    G%geoLonCv(i,J) = grid_LonT(i)
    G%geoLatCv(i,J) = grid_latB(J)
    
    i_global = i+I_offset-(G%isg-1)
    dlon = real(2.0*i_global)*dLonmaxsg + a*(cos(real(2*(i_global))*PI/N/2.0)-1.0) - &
           (real(2.0*(i_global-1))*dLonmaxsg + a*(cos(real(2*(i_global-1))*PI/N/2.0)-1.0))
    G%dxCv(i,J) = G%Rad_Earth * (dLon*PI_180) * COS( G%geoLatCv(i,J)*PI_180 )
    G%dyCv(i,J) = G%Rad_Earth * dLat*PI_180
  enddo; enddo
  do j=jsd,jed ; do I=IsdB,IedB
    G%geoLonCu(I,j) = grid_lonB(I)
    G%geoLatCu(I,j) = grid_LatT(j)

    i_global = i+I_offset-(G%isg-1)
    dlon = real(2.0*i_global+1)*dLonmaxsg + a*(cos(real(2*(i_global)+1)*PI/N/2.0)-1.0) - &
           (real(2.0*i_global-1)*dLonmaxsg + a*(cos(real(2*(i_global)-1)*PI/N/2.0)-1.0))
    G%dxCu(I,j) = G%Rad_Earth * dLon*PI_180 * COS( G%geoLatCu(i,J)*PI_180 )
    G%dyCu(I,j) = G%Rad_Earth * dLat*PI_180
  enddo; enddo
  do j=jsd,jed ; do i=isd,ied
    G%geoLonT(i,j) = grid_LonT(i)
    G%geoLatT(i,j) = grid_LatT(j)
    
    i_global = i+I_offset-(G%isg-1)
    dlon = real(2.0*i_global)*dLonmaxsg + a*(cos(real(2*(i_global))*PI/N/2.0)-1.0) - &
           (real(2.0*(i_global-1))*dLonmaxsg + a*(cos(real(2*(i_global-1))*PI/N/2.0)-1.0))
    G%dxT(i,j) = G%Rad_Earth * dLon*PI_180 * COS( G%geoLatT(i,j)*PI_180 )
    G%dyT(i,j) = G%Rad_Earth * dLat*PI_180
    G%areaT(i,j) = G%dxT(i,j) * G%dyT(i,j)
  enddo; enddo
  call callTree_leave("set_grid_metrics_spherical_nonuniformx()")
end subroutine set_grid_metrics_spherical_nonuniformx
```

**Comment by adcroft** [comment]
Global indexing is described in the documentation at http://noaa-gfdl.github.io/MOM6/APIs/db/dde/Horizontal_indexing.html so I am closing this issue.
