### ISSUE TITLE
Compiling on MacBook M2 chip

### ISSUE THREAD

**Issue by syou83syou83** [NOAA-GFDL/MOM6-examples#446]
Dear MOM6 community,

I am new to both Fortran and MOM6 and would like to run some test cases on my MacBook with M2 chip. I wonder if `osx-gcc10.mk` still works because the `bash compileSIS2.bash` didn't go through, outputting the following errors:

```
duplicate symbol '_main' in:
    coupler_main.o
    icebergs_driver.o
ld: 1 duplicate symbol for architecture arm64
collect2: error: ld returned 1 exit status
```

Or is it because I did something wrong? (I followed this instruction: https://github.com/NOAA-GFDL/MOM6-examples/wiki/Compiling-on-MacBook-M1-chip-using-conda-environment) Please let me know if you need more info. Thank you very much for your help!

Best,
Si

**Comment by marshallward** [comment]
I don't think this is a template problem.  I believe this is because of a recent change to the directory tree of the icebergs repository.

In the `list_paths` line, you will want to replace `icebergs` with `icebergs/src`.  This will remove the driver in `icebergs/driver` and should eliminate the error.
